version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: confy-sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    restart: unless-stopped
    networks:
      - confy-network
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  confy-network:
    driver: bridge
